name: Build Forge mod with Gradle
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Set up JDK 8
      uses: actions/setup-java@v5
      with:
          distribution: 'temurin'
          java-version: 8

    - name: Compile with Gradle
      run: ./gradlew build

    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v4
      with:
          name: Simple-Female-Gender
          path: build/libs/*.jar
